CREATE DATABASE IF NOT EXISTS dbms;

USE dbms;

DROP TABLE IF EXISTS USER_RECIPES;
DROP TABLE IF EXISTS RECIPES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
	USER_ID INTEGER AUTO_INCREMENT,
	USER_EMAIL VARCHAR(300) UNIQUE NOT NULL,
	USER_PASSWORD VARCHAR(300) NOT NULL,
	SIGNUP_DATE DATE,

	PRIMARY KEY (USER_ID)
);


CREATE TABLE RECIPES (
	RECIPE_ID INTEGER AUTO_INCREMENT,
	RECIPE_TITLE VARCHAR(300),
	RECIPE_INGREDIENTS VARCHAR(300),
	RECIPE_PROCEDURE TEXT(16383),
	RECIPE_IMAGE VARCHAR(300),

	PRIMARY KEY (RECIPE_ID)
);

CREATE TABLE USER_RECIPES (
	USER_ID INTEGER,
	RECIPE_ID INTEGER,

	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
	FOREIGN KEY (RECIPE_ID) REFERENCES RECIPES (RECIPE_ID)
);
